### ISSUE TITLE
Add OS X Pod Platform

### ISSUE THREAD

**Issue by jbeemster** [samskiter/KiteJSONValidator#11]
Would it be possible to add OSX as a deployment platform in the podspec?

**Comment by samskiter** [comment]
Hi, it should be fine so long as it compiles ok. I haven't attempted to build for OSX, have you?

**Comment by jbeemster** [comment]
I have not yet but will do so now.

**Comment by jbeemster** [comment]
So the only thing that could trip an OSX version up is the: `#import <UIKit/UIKit.h>` located here https://github.com/samskiter/KiteJSONValidator/blob/develop/Tests/Tests-Prefix.pch#L8

But that only relates to the test suite, as far as building the core library under OSX I did not have any issues!

**Comment by samskiter** [comment]
Do you have any idea how to set the cocoapod file up? if you have experience it might speed things up for me

**Comment by samskiter** [comment]
Just got released 0.2.3 to cocoapods. Let me know how you get on and thanks for you your contribution :+1:

**Comment by jbeemster** [comment]
Thanks @samskiter and my pleasure!
